### ISSUE TITLE
SIGIR 2022 paper HCCF on self-supervised GNN

### ISSUE THREAD

**Issue by akaxlh** [ChandlerBang/awesome-self-supervised-gnn#22]
Thank you for your great work! Our model HCCF accepted by SIGIR'2022 is on self-supervised GNNs. It would be nice if you include the paper in the list.
[SIGIR 2022] Hypergraph Contrastive Collaborative Filtering
Link: https://arxiv.org/pdf/2204.12200.pdf

**Comment by ChandlerBang** [comment]
Added. Thank you!
