### ISSUE TITLE
Missing Generalized Laplacian Eigenmaps in Neurips 2022

### ISSUE THREAD

**Issue by allenhaozhu** [ChandlerBang/awesome-self-supervised-gnn#29]
and  COSTA: Covariance-Preserving Feature Augmentation for Graph Contrastive Learning has been accepted by KDD2022. Thanks for your help.

**Comment by yyou1996** [comment]
Hi @allenhaozhu,

Thanks for the information! I have added these two papers to the 2022 collection.

**Comment by allenhaozhu** [comment]
@yyou1996 Thank you very much.
